# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=16)),
                ('grade', models.CharField(default='', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(default='', max_length=8)),
                ('email', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='T_Img_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('img_path', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='takes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seesaw.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seesaw.student')),
            ],
        ),
        migrations.CreateModel(
            name='teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seesaw.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='teaches',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seesaw.teacher'),
        ),
        migrations.AddField(
            model_name='t_img_item',
            name='teaches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seesaw.teaches'),
        ),
    ]
