# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0003_auto_20170731_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
    ]
