# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0004_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='S_Img_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('img_path', models.CharField(default='', max_length=128)),
                ('takes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seesaw.takes')),
            ],
        ),
    ]
