# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0005_s_img_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s_img_item',
            name='takes',
        ),
        migrations.AddField(
            model_name='s_img_item',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seesaw.course'),
        ),
        migrations.AddField(
            model_name='s_img_item',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seesaw.student'),
        ),
    ]
