# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0006_auto_20170731_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(default='', max_length=8),
        ),
    ]
