# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0009_un_group_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=256)),
                ('homework_ddl', models.DateTimeField(default='')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seesaw.course')),
            ],
        ),
    ]
