# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0010_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
