# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0011_course_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(default='', max_length=16),
        ),
    ]
