# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0013_auto_20170805_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='homework_ddl',
        ),
    ]
