# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0016_section_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=256)),
                ('img_path', models.CharField(default='', max_length=128)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seesaw.section')),
            ],
        ),
    ]
