# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0017_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seesaw.student'),
        ),
    ]
