# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0019_homework_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='create_time',
        ),
    ]
