# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0020_remove_homework_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='create_time',
            field=models.CharField(default='', max_length=32),
        ),
    ]
