# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0021_homework_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_img_item',
            name='create_time',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='t_img_item',
            name='create_time',
            field=models.CharField(default='', max_length=32),
        ),
    ]
