# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0022_auto_20170808_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_img_item',
            name='content',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='t_img_item',
            name='content',
            field=models.CharField(default='', max_length=256),
        ),
    ]
