# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0023_auto_20170808_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='get_star',
            field=models.BooleanField(default=False),
        ),
    ]
