# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seesaw', '0024_homework_get_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='get_star',
            field=models.IntegerField(default=0),
        ),
    ]
